# Generated by Django 4.2.6 on 2023-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_amortizationschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="")),
            ],
        ),
    ]
