# Generated by Django 4.2.6 on 2023-10-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_loanexcel"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="loan_number",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amortizationschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="loans.loan"
            ),
        ),
    ]
